import Head from "next/head"
import { Title } from "@mantine/core"

export default function Home() {
    return (
        <>
            <Head>
                <title>Qizz Admin</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Title order={1}>Qizz Admin</Title>
            </main>
        </>
    )
}
